version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - unique
          - not_null
      - name: channel_name
        tests:
          - not_null

  - name: dim_channels
    columns:
      - name: channel_name
        tests:
          - unique
          - not_null

  - name: fct_image_detections
    columns:
      - name: message_id
        tests:
          - not_null
      - name: object_class
        tests:
          - not_null
